from .cfg_parallel import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .verbose_debug import NODE_CLASS_MAPPINGS as VD_CLASS_MAPPINGS
from .verbose_debug import NODE_DISPLAY_NAME_MAPPINGS as VD_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS.update(VD_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(VD_DISPLAY_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
